# Dockerfile para el backend
FROM node:18

# Crear y establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos de proyecto
COPY package*.json ./
RUN npm install

# Copiar el archivo .env al contenedor
COPY .env ./

# Copiar el resto del proyecto
COPY . .

# Exponer el puerto en el que se ejecuta la aplicación
EXPOSE 3001

# Comando para iniciar la aplicación
CMD ["npm", "start"]
